### ISSUE TITLE
W3c Validation for HTML fails if the response is not a valid SOAP response

### ISSUE THREAD

**Issue by brijeshkumarmaurya** [jcabi/jcabi-w3c#10] opened 2015-01-27 07:44 UTC
Sometimes, if the W3C online validation service is down or busy, one may get a different status code e.g. 502, 500 etc. Consequently, the response text sent is also different and is not in SOAP format, but in text/html format.

However, the program tries to parse the response as an XML (jcabi.http). Specifically asserting using XPATHs /m:validity etc. Since, the response is HTML and not SOAP/XML, the Xerces XML parsing fails.

Is this by design, or should a non 200/OK response handled in a different way?

<hr id='w'>

**Comment by yegor256** [comment] 2015-01-27 16:57
@brijeshkumarmaurya this is more or less by design. SOAP is supposed to come back from the web service. 50x response is a server failure and we fail immediately as soon as we see it. What do you think would be a better scenario?

**Comment by brijeshkumarmaurya** [comment] 2015-01-29 07:43
Hi,
The validate() API throws an IOException, so we are forced to catch it (or rethrow). But the problem is when a response different than XML is obtained, we get XML parsing exception which is of type org.xml.sax.SAXParseException, so our catch block will fail when this exception occurs (unless we are catching Exception which mostly is not the case)

Ideally, the API should wrap every exception to IOException itself with proper cause, detail, explanation and reason set so that the API can be used with confidence without having any side effects. The ValidationResponse may include methods to provide such additional information.

Also on a side note the main page for jacabi-w3c should mention all the dependencies (only minimal set) to run this validation service properly. The minimal set of jars:
aspectjrt-1.8.4.jar
httpmime-4.3.jar
jcabi-log-0.15.1.jar
jcabi-xml-0.13.jar
slf4j-api-1.7.5.jar
hamcrest-core-1.3.jar
jcabi-aspects-0.20.1.jar
jcabi-manifests-1.1.jar
jersey-client-1.18.1.jar
slf4j-log4j12-1.7.7.jar
hamcrest-library-1.3.jar
jcabi-http-1.9.2.jar
jcabi-matchers-1.3.jar
jersey-core-1.18.1.jar
validation-api-1.1.0.Final.jar
httpcore-4.3.jar
jcabi-immutable-1.3.jar
jcabi-w3c-2.0-SNAPSHOT.jar
log4j-1.2.17.jar

**Comment by yegor256** [comment] 2015-01-29 16:59
@brijeshkumarmaurya yes, I agree, we should throw only `IOException`. let us try to fix this.

**Comment by dmarkov** [comment] 2015-01-30 08:27
@nhekfqn the task is yours

**Comment by nhekfqn** [comment] 2015-02-08 18:50
@yegor256 mentioned exception is checked and is never thrown from DefaultHtmlValidator.validate method. What exactly should be done in this task?

**Comment by yegor256** [comment] 2015-02-08 18:52
@nhekfqn the problem here is that when the server returns 503 we throw something that is not `IOException` and it's confusing for users

**Comment by nhekfqn** [comment] 2015-02-08 19:17
@yegor256 I read the discussion and undestand that, but @brijeshkumarmaurya complained about org.xml.sax.SAXParseException which is checked exception and is never thrown in code of the project, as I can see. Does this issues belongs to another project?

**Comment by yegor256** [comment] 2015-02-08 19:27
@nhekfqn we have to make sure that no matter what kind of problem is happening on the server, we always throw `IOException`. At the moment, we ignore the situation when 503 is returned and trying to parse HTTP body as XML. Of course, SAX fails and we throw a runtime exception. It's our bug

**Comment by nhekfqn** [comment] 2015-02-08 19:59
@dmarkov Please find someone else to do this task.

**Comment by dmarkov** [comment] 2015-02-09 07:02
> @dmarkov Please find someone else to do this task.

@nhekfqn I will try to find someone else

**Comment by dmarkov** [comment] 2015-02-23 08:19
@apocarteres please proceed, it's yours

**Comment by dmarkov** [comment] 2015-09-10 13:39
@kpbird This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by kpbird** [comment] 2015-09-14 18:55
@dmarkov  @brijeshkumarmaurya  Do we have steps or situation to reproduce this bug ?

**Comment by dmarkov** [comment] 2015-09-16 08:08
> @dmarkov  @brijeshkumarmaurya  Do we have steps or situation to reproduce this bug ?

@kpbird please ask @brijeshkumarmaurya, the reporter of the bug

**Comment by dmarkov** [comment] 2015-09-28 08:07
@kpbird the task is your hands for the last 17 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

-30 to your rating, your total score is [-30](http://www.netbout.com/b/35593?open=rating)

**Comment by dmarkov** [comment] 2015-10-01 08:31
@kpbird the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html); -60 added to your rating, at the moment it is: [-120](http://www.netbout.com/b/35593?open=rating)

**Comment by dmarkov** [comment] 2015-10-30 13:55
@prondzyn it's your task, go ahead

**Comment by prondzyn** [comment] 2015-11-06 22:40
@dmarkov PR #18 prepared

**Comment by dmarkov** [comment] 2015-11-16 09:10
> @dmarkov PR #18 prepared

@prondzyn thanks

**Comment by dmarkov** [comment] 2015-11-16 09:12
@prondzyn you're working with this issue for 16 days already; -30 added to your rating, at the moment it is: [+45](http://www.netbout.com/b/35715?open=rating)

**Comment by prondzyn** [comment] 2015-11-16 11:42
@dmarkov it is not fair. I prepared the PR #18 10 days ago, and the PR was assigned by you to @dmzaytsev 3 days ago. So it was hanging on nobody for 7 days. No it is waiting for 3 days on @yegor256 reply to [this comment](https://github.com/jcabi/jcabi-w3c/pull/18#discussion_r44809763).

**Comment by yegor256** [comment] 2015-11-16 22:51
@prondzyn take a look: http://at.teamed.io/policy.html#10 Also, keep in mind that it's always your responsibility to close a task, no matter who else is involved, see http://at.teamed.io/policy.html#7

**Comment by prondzyn** [comment] 2015-11-17 04:32
@dmarkov more time. I would like to finish this task.

**Comment by dmarkov** [comment] 2015-11-17 07:09
> @dmarkov more time. I would like to finish this task.

@prondzyn OK, no problem, take your time

**Comment by prondzyn** [comment] 2015-11-27 06:12
@dmarkov I still need more time as PR #18 is hanging now on @yegor256 confirmation.

**Comment by dmarkov** [comment] 2015-11-27 08:07
> @dmarkov I still need more time as PR #18 is hanging now on @yegor256 confirmation.

@prondzyn yeah, I know, take your time

**Comment by prondzyn** [comment] 2015-12-07 06:57
@dmarkov I still need more time as PR #18 is hanging now on @yegor256 confirmation.

**Comment by dmarkov** [comment] 2015-12-07 11:35
> @dmarkov I still need more time as PR #18 is hanging now on @yegor256 confirmation.

@prondzyn sure, take your time, I know about this pause

**Comment by prondzyn** [comment] 2015-12-08 11:03
@dmarkov PR #18 merged

**Comment by dmarkov** [comment] 2015-12-08 13:47
> @dmarkov PR #18 merged

@prondzyn ask ticket reporter to close it

**Comment by prondzyn** [comment] 2015-12-08 13:51
@brijeshkumarmaurya please close the ticket

**Comment by dmarkov** [comment] 2015-12-10 07:02
@brijeshkumarmaurya 2 puzzles were created here: `10-1838eb03`, `10-80fda63a`/#19

**Comment by prondzyn** [comment] 2015-12-13 16:08
@brijeshkumarmaurya please, close the ticket

**Comment by prondzyn** [comment] 2015-12-14 19:44
@dmarkov I do not think @brijeshkumarmaurya will close the ticket. It does not see as an active account. I see only one commit from 27 Jan 2015 and no more activity. Whan now?

**Comment by dmarkov** [comment] 2015-12-17 08:11
> @dmarkov I do not think @brijeshkumarmaurya will close the ticket. It does not see as an active account. I see only one commit from 27 Jan 2015 and no more activity. Whan now?

@prondzyn please ask @yegor256 to do something about it

**Comment by prondzyn** [comment] 2015-12-17 08:24
@yegor256 what should I do now?

**Comment by yegor256** [comment] 2015-12-17 21:01
@dmarkov please close it

**Comment by dmarkov** [comment] 2015-12-18 07:56
> @dmarkov please close it

@yegor256 OK, the issue is closed as requested

**Closed by dmarkov** 2015-12-18 07:56 UTC
Labels: 30 mins, @prondzyn, bug, DEV

**Comment by dmarkov** [comment] 2015-12-21 08:04
@prondzyn paid, thanks, added **30 mins** to your account, payment `AP-6ES90066WA9794342`, 1172 hours and 17 mins was spent

+30 to your rating, your total score is [+90](http://www.netbout.com/b/35715?open=rating)

**Comment by dmarkov** [comment] 2016-03-08 13:52
@brijeshkumarmaurya the last puzzle `20-b02d0160`/#32 solved
